// Expo config plugin entry point. The compiled plugin lives in plugin/build
// (generated by `tsc -p plugin/tsconfig.json` during `prepare`).
const plugin = require('./plugin/build/index.js');

module.exports = plugin.default || plugin;
